---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/reservations":
    get:
      summary: list reservations
      tags:
      - Reservations
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              example: []
        '401':
          description: Unauthorized
    post:
      summary: Create reservations
      tags:
      - Reservations
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: successful
          content:
            application/json:
              example:
                id: 67
                start_date: '2023-01-16'
                end_date: '2023-01-16'
                user_id: 1354
                tour_id: 246
                created_at: '2023-06-20T21:06:31.913Z'
                updated_at: '2023-06-20T21:06:31.913Z'
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reservation:
                  type: object
                  properties:
                    tour_id:
                      type: integer
                    start_date:
                      type: string
                      format: date
                    end_date:
                      type: string
                      format: date
              required:
              - start_date
              - end_date
              - tour_id
  "/reservations/{id}":
    get:
      summary: Show reservation
      tags:
      - Reservations
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              example:
                id: 68
                start_date: '2023-02-12'
                end_date: '2023-04-13'
                user_id: 1360
                tour_id: 249
                created_at: '2023-06-20T21:06:31.959Z'
                updated_at: '2023-06-20T21:06:31.959Z'
                tour:
                  id: 249
                  name: Tour 7
                  city: Canada 7
                  price: '245.0'
                  video: https://www.youtube.com/watch?v=XxuPlSW4t6M&list=PLCawOXF4xaJLb9HwPWiizGBNupJszY6bR
                  status: false
                  user_id: 1361
                  created_at: '2023-06-20T21:06:31.954Z'
                  updated_at: '2023-06-20T21:06:31.957Z'
                  des: Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta
                    a possimus impedit modi quia? Incidunt?
        '401':
          description: Unauthorized
  "/tours":
    get:
      summary: list tours
      tags:
      - Tours
      responses:
        '200':
          description: Successful
          content:
            application/json:
              example:
              - id: 56
                name: Obudu tour
                city: Ibom
                price: '245.0'
                video: Do it now or die regretting
                status: false
                user_id: 289
                created_at: '2023-06-20T14:00:22.085Z'
                updated_at: '2023-06-20T14:00:22.085Z'
                des: 
                image_url: 
              - id: 252
                name: Tour 10
                city: Canada 10
                price: '245.0'
                video: https://www.youtube.com/watch?v=XxuPlSW4t6M&list=PLCawOXF4xaJLb9HwPWiizGBNupJszY6bR
                status: false
                user_id: 1367
                created_at: '2023-06-20T21:06:32.001Z'
                updated_at: '2023-06-20T21:06:32.007Z'
                des: Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta
                  a possimus impedit modi quia? Incidunt?
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBYk09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f040b0fbe88e062cb79af5c376b997f7ce783690/dominos.jpg"
    post:
      summary: Create tour
      tags:
      - Tours
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: successful
          content:
            application/json:
              example:
                id: 253
                name: Joyland
                city: Lahore
                price: '30.0'
                video: This is the video
                status: false
                user_id: 1368
                created_at: '2023-06-20T21:06:32.027Z'
                updated_at: '2023-06-20T21:06:32.027Z'
                des: Just a small place to fun
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                city:
                  type: string
                price:
                  type: integer
                des:
                  type: string
                video:
                  type: string
                image:
                  type: string
                  format: binary
              required:
              - name
              - city
              - price
              - des
  "/tours-all":
    get:
      summary: list all tours including removed tours
      tags:
      - Tours
      responses:
        '200':
          description: Successful
          content:
            application/json:
              example:
              - id: 56
                name: Obudu tour
                city: Ibom
                price: '245.0'
                video: Do it now or die regretting
                status: false
                user_id: 289
                created_at: '2023-06-20T14:00:22.085Z'
                updated_at: '2023-06-20T14:00:22.085Z'
                des: 
                image_url: 
              - id: 254
                name: Tour 11
                city: Canada 11
                price: '245.0'
                video: https://www.youtube.com/watch?v=XxuPlSW4t6M&list=PLCawOXF4xaJLb9HwPWiizGBNupJszY6bR
                status: false
                user_id: 1371
                created_at: '2023-06-20T21:06:32.052Z'
                updated_at: '2023-06-20T21:06:32.056Z'
                des: Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta
                  a possimus impedit modi quia? Incidunt?
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBYlE9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--10ef6c4caff4dda8d6b58584890cc2d63b7ed8f7/dominos.jpg"
  "/tours/{id}":
    get:
      summary: Show tour
      tags:
      - Tours
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              example:
                id: 255
                name: Tour 12
                city: Canada 12
                price: '245.0'
                video: https://www.youtube.com/watch?v=XxuPlSW4t6M&list=PLCawOXF4xaJLb9HwPWiizGBNupJszY6bR
                status: false
                user_id: 1373
                created_at: '2023-06-20T21:06:32.074Z'
                updated_at: '2023-06-20T21:06:32.078Z'
                des: Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta
                  a possimus impedit modi quia? Incidunt?
        '401':
          description: Unauthorized
  "/users":
    post:
      summary: Create user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - name
              - email
              - password
  "/login":
    post:
      summary: Authenticate user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: user authenticated
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/users/{id}":
    get:
      summary: Get user by id
      tags:
      - Users
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              example:
                id: 1380
                name: user 32
                email: user-test32@gmail.com
        '401':
          description: Unauthorized
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/api/v1
